title: Cole Man Blastic
description: This is my website where I put all of my cool web projects. I guess right now you could say it is the project.
url: https://cole-man-blastic.github.io

collections:
  articles:
    output: true
    permalink: /blog/posts/:path
  canvas-projects:
    output: true
    permalink: /projects/:path
